### ISSUE TITLE
ppingbeat panics with stack trace

### ISSUE THREAD

**Issue by kofemann** [joshuar/pingbeat#36]
```
# ./pingbeat -c pingbeat.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaf5ae1]

goroutine 120 [running]:
github.com/joshuar/pingbeat/beater.RecvPings(0xb897, 0xc4201fa3f0, 0xc420183170, 0xc420188640)
	/home/tigran/eProjects/go/src/github.com/joshuar/pingbeat/beater/pingbeat.go:207 +0x1e1
created by github.com/joshuar/pingbeat/beater.(*Pingbeat).Run
	/home/tigran/eProjects/go/src/github.com/joshuar/pingbeat/beater/pingbeat.go:116 +0xa0c

```

my config:

```
pingbeat:
  # Defines how often a ping is sent to a target
  period: 1s
  # Whether to send pings over IPv4
  useipv4: true
  # Whether to send pings over IPv6
  useipv6: true
  targets:
    - name: "cloud01"
      tags: "cloud01"
      desc: "cloud host 01"
    - name: "cloud02"
      tags: "cloud02"
      desc: "cloud host 02"
    - name: "cloud03"
      tags: "cloud03"
      desc: " cloud host 03"
    - name: "cloud04"
      tags: "cloud04"
      desc: "cloud host 04"
    - name: "cloud05"
      tags: "ycloud05"
      desc: "cloud host 05"
    - name: "cloud06"
      tags: "cloud06"
      desc: "cloud host 06"

output.elasticsearch:
  template.enabled: false
  hosts: ["es-lab:9200"]

```
