### ISSUE TITLE
Missing target.description

### ISSUE THREAD

**Issue by nommuh** [joshuar/pingbeat#37]
I'm trying to use the default configuration and I'm expecting _target.description_ in ES but it's not available.

```
...
pingbeat:
  # Defines how often a ping is sent to a target
  period: 1s
  # Whether to send pings over IPv4
  useipv4: true
  # Whether to send pings over IPv6
  useipv6: false
  targets:
    - name: "127.0.0.1"
      tags: "localhost"
      desc: "there's no place like home"
...
```

Running `pingbeat -e -d "*" -c /etc/pingbeat/pingbeat.yml`. Publish doesn't show the field either.

```
...
2018/10/04 14:32:42.891583 client.go:214: DBG  Publish: {
  "@timestamp": "2018-10-04T14:32:42.891Z",
  "beat": {
    "hostname": "my-host",
    "name": "my-host",
    "version": "5.6.10"
  },
  "logzio_codec": "json",
  "rtt": 0.036898,
  "target": {
    "addr": "127.0.0.1",
    "name": "127.0.0.1",
    "tags": [
      "localhost"
    ]
  },
  "token": "aslkdakjaslasdklsaldjaslkjdlasjdalsjdlasjdlaksjd",
  "type": "my-host-pingbeat"
}
...
```

What am I missing?
